from collections import defaultdict
from gtnlplib import constants

theta_hand_original = defaultdict(float,
                          {('worldnews', 'worldnews'): 1.,
                           ('worldnews', 'news'): .5,
                           ('worldnews', 'world'): .5,
                           ('science', 'science'): 1.,
                           ('askreddit', 'askreddit'): 1.,
                           ('askreddit', 'ask'): 0.5,
                           ('iama', 'iama'): 1,
                           ('todayilearned', 'til'): 1.,
                           ('todayilearned', 'todayilearned'): 1.,
                           ('iama', constants.OFFSET): 0.1
                           })

# add some more weights to this for deliverable 2.3
theta_hand = defaultdict(float,{('worldnews','worldnews'):2.,
                                ('worldnews','military'):2.,
                                ('worldnews','jobs'):.5,
                                ('worldnews','news'):.5,
                                ('worldnews','world'):.5,
                                ('worldnews','forces'):1.,
                                ('worldnews','europe'):1.,
                                ('worldnews','asia'):1.,
                                ('worldnews','muslim'):1.,
                                ('worldnews','equality'):1.,
                                ('science','science'):1.,
                                ('science','model'):0.5,
                                ('science','abstract'):1.,
                                ('science','specialty'):0.5,
                                ('science','phd'):2.,
                                ('science','masters'):1.,
                                ('science','degree'):0.5,
                                ('science','research'):2.,
                                ('science','researcher'):2.,
                                ('science','researchers'):2.,
                                ('science','scientist'):2.,
                                ('science','scientists'):2.,
                                ('askreddit','askreddit'):1.,
                                ('askreddit','ask'):0.5,
                                ('science','detect'):0.5,
                                ('iama','iama'):4,
                                ('iama','ama'):4,
                                ('todayilearned','til'):5.,
                                ('todayilearned','todayilearned'):1.,
                                ('iama',constants.OFFSET):1,
                         })
